### ISSUE TITLE
missing .npz files for famous dataset

### ISSUE THREAD

**Issue by Linusnie** [mabaorui/NeuralPull#18]
hi, many thanks for you work on this method

I'm looking into reproducing your results on the Famous dataset. But I noticed that the .npz files are missing from the download link in the readme (https://drive.google.com/drive/folders/1qre9mgJNCKiX11HnZO10qMZMmPv_gnh3?usp=sharing). Would you be able to add those files in? 

I also tried recreating the point clouds with `python sample_query_point.py --out_dir /home/linus/workspace/data/neural_pull/famous_new/ --input_dir /home/linus/workspace/data/points2surf/famous_noisefree/04_pts/ --dataset famous`, but I get the error
```
/home/linus/workspace/data/neural_pull/famous_new/3DBenchy.npz
Traceback (most recent call last):
  File "/home/linus/workspace/NeuralPull/sample_query_point.py", line 124, in <module>
    point_idx = np.random.choice(pointcloud.shape[0], POINT_NUM_GT, replace = False)
  File "numpy/random/mtrand.pyx", line 1000, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'
```
Since the 3DBenchy dataset has less than `POINT_NUM_GT`(=20000) points. Could you clarify what value of `POINT_NUM_GT` was used for the famous dataset?

**Comment by kbrian8** [comment]
HI  @Linusnie , did you manage to resolve the above issue? I'm facing the same.

**Comment by Linusnie** [comment]
@kbmufti kind of, I moved on to using the pytorch version, where the pre-processing is applied automatically if you pass in a .xyz file [see here](https://github.com/mabaorui/NeuralPull-Pytorch/blob/master/models/dataset.py#L19)

I should say the sampling settings in the pytorch repo are slightly different from the tensorflow implementation, so it would still be nice to have the original `.npy` files for reproducing the paper results. For example: in the pytorch repo the local sigma scale is set automatically based on the number of points, while it's fixed in tensorflow. The pytorch repo also auto-scales the point cloud to fit in a 1x1x1 bounding box centered at 0.

**Comment by kbrian8** [comment]
@Linusnie , Thank you for you response, What version of python are you using? I am getting dependencies conflicts

**Comment by Linusnie** [comment]
I followed the instructions here https://github.com/mabaorui/NeuralPull/issues/2#issuecomment-880653009
